apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-plugins
spec:
  accessModes:
    - ReadWriteMany
  {{ if .Values.pvc.plugins.storageClass }}
  storageClassName: {{ .Values.pvc.plugins.storageClass }}
  {{ end}}
  resources:
    requests:
      storage: {{ .Values.pvc.plugins.storageSize }}Gi