kind: Service
apiVersion: v1
metadata:
  name: {{.Release.Name}}-lb
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8888
      targetPort: 8888
  selector:
    app: {{.Release.Name}}
  externalTrafficPolicy: Local
  loadBalancerIP: {{ .Values.service.loadbalancerIp }}
  type: LoadBalancer