{{ if .Values.serviceMonitor.enabled }}
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: fritzbox-monitoring
  labels:
    app: fritzbox-monitoring
spec:
  selector:
    matchLabels:
      app: fritzbox-monitoring
  endpoints:
  - port: web
    path: /metrics 
{{ end }}