apiVersion: v1
kind: Service
metadata:
  name: fritzbox-monitoring-clusterip
  labels:
    app: fritzbox-monitoring
spec:
  selector:
    app: fritzbox-monitoring
  ports:
  - port: 9042
    targetPort: 9042
    name: web
