kind: Service
apiVersion: v1
metadata:
  name: hedgedoc-lb
spec:
  selector:
    app: hedgedoc
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  externalTrafficPolicy: Local
  loadBalancerIP: {{ .Values.service.ip }}
  type: LoadBalancer