apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeassistant
  labels:
    app: homeassistant
spec:
  replicas: 1
  revisionHistoryLimit: 3
  progressDeadlineSeconds: 600
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      containers:
        - name: homeassistant
          image: homeassistant/home-assistant:2023.7
          imagePullPolicy: IfNotPresent
          {{ if .Values.deployment.sleepStart }}
          # Just spin & wait forever
          command: [ "/bin/bash", "-c", "--" ]
          args: [ "while true; do sleep 30; done;" ]
          {{ end }}
          {{ if .Values.deployment.hostNetwork }}
          hostNetwork: true
          {{ end }}
          env:
            - name: EULA
              value: "TRUE"
          volumeMounts:
            - mountPath: "/config"
              name: data
            - mountPath: "/config/configuration.yaml"
              subPath: "configuration.yaml"
              name: config
          ports:
            - containerPort: 8123
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data
        - name: config
          configMap:
            name: settings
