apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{lower .Release.Name}}
spec:
  replicas: 1
  revisionHistoryLimit: 5
  strategy:
    type: {{.Values.deployment.strategy.type}}
  selector:
    matchLabels:
      app: {{lower .Release.Name}}
  template:
    metadata:
      labels:
        app: {{lower .Release.Name}}
      name: {{lower .Release.Name}}
    spec:
      containers:
        - image: {{ .Values.deployment.image.location }}:{{ .Values.deployment.image.tag }}
          imagePullPolicy: IfNotPresent
          name: ollama
          {{ if .Values.deployment.sleepStart }}
          # Just spin & wait forever
          command: [ "/bin/bash", "-c", "--" ]
          args: [ "while true; do sleep 30; done;" ]
          {{ end }}
          ports:
            - containerPort: 11434
              name: http
              protocol: TCP
          resources:
            {{- if .Values.deployment.resources.limits.enabled }}
            limits:
              {{- if .Values.deployment.resources.limits.enabledCpuLimit}}  
              cpu: {{.Values.deployment.resources.limits.cpu}}m{{end}}
              memory: {{.Values.deployment.resources.limits.memory}}M {{end}}
            {{- if .Values.deployment.resources.requests.enabled }}
            requests:
              cpu: {{.Values.deployment.resources.requests.cpu}}m
              memory: {{.Values.deployment.resources.requests.memory}}M {{end}}
          volumeMounts:
            - name: storage
              mountPath: /root/.ollama
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: {{lower .Release.Name}}-storage