kind: Service
apiVersion: v1
metadata:
  name: {{.Release.Name}}
spec:
  selector:
    app: {{.Release.Name}}
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  externalTrafficPolicy: Local
  loadBalancerIP: {{ .Values.service.ip }}
  type: LoadBalancer