apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}
spec:
  type: ClusterIP
  selector:
    app: {{.Release.Name}}
  ports:
    - port: 1883
      targetPort: mqtt
      protocol: TCP
      name: mqtt