apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{lower .Release.Name}}
spec:
  replicas: 1
  revisionHistoryLimit: 5
  strategy:
    type: {{.Values.deployment.strategy.type}}
  selector:
    matchLabels:
      app: {{lower .Release.Name}}
  template:
    metadata:
      labels:
        app: {{lower .Release.Name}}
      name: {{lower .Release.Name}}
    spec:
      initConmtainers:
        - name: copy
          image: busybox:1.28
          command: ["/bin/sh", "-c", "cp /tmp/feed/feeds.txt /tmp/storage/feeds.txt/"]
          volumeMounts:
            - name: storage
              mountPath: /tmp/storage
            - name: feeds
              mountPath: /tmp/feed/
      containers:
        - image: {{ .Values.deployment.image.location }}:{{ .Values.deployment.image.tag }}
          imagePullPolicy: IfNotPresent
          name: rss
          {{ if .Values.deployment.sleepStart }}
          # Just spin & wait forever
          command: [ "/bin/bash", "-c", "--" ]
          args: [ "while true; do sleep 30; done;" ]
          {{ end }}
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          env:
            - name: APP_NAME
              value: "{{.Values.configuration.appName}}"
          resources:
            {{ if .Values.deployment.resources.limits.enabled }}
            limits:  
              cpu: {{.Values.deployment.resources.limits.cpu}}m
              memory: {{.Values.deployment.resources.limits.memory}}M {{end}}
            {{ if .Values.deployment.resources.requests.enabled }}
            requests:
              cpu: {{.Values.deployment.resources.requests.cpu}}m
              memory: {{.Values.deployment.resources.requests.memory}}M {{end}}
          volumeMounts:
            - name: storage
              mountPath: /app/storage
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: {{lower .Release.Name}}-storage
        - name: feeds
          configMap:
            name: {{lower .Release.Name}}-feeds