deployment:
  sleepStart: false
  image:
    location: vegardit/gitea-act-runner
    tag: dind-latest
  withDockerSocket: true
  dockersocket: /var/run/docker.sock

pvc:
  data:
    accessMode: ReadWriteOnce
    #only applied when set
    storageClass:
    #size in Gi
    storageSize: 5

configuration:
  instanceUrl: "overlay_me"
  registrationToken: "overlay_me"