{{- range .Values.ingress }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $.Release.Name }}-{{ .name }}-ingress
  annotations:
    cert-manager.io/cluster-issuer: {{.issuer}}
    kubernetes.io/ingress.class: {{.ingressClass}}
    traefik.ingress.kubernetes.io/router.entrypoints: "web, websecure"
    traefik.ingress.kubernetes.io/router.tls: "true"
    {{- range $key, $val := .additionalAnnotations }}
    {{ $key }}: "{{ $val }}"
    {{- end }}
spec:
  tls:
    - hosts:
        - {{ .name }}
      secretName: {{ .name }}
  rules:
    - host: {{ .name }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ lower $.Release.Name }}-clusterip
                port:
                  number: 80
---
{{- end}}