apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-steamcmd
spec:
  accessModes:
    - {{ .Values.pvc.steamcmd.accessMode }}
  {{ if .Values.pvc.steamcmd.storageClass }}
  storageClassName: {{ .Values.pvc.steamcmd.storageClass }}
  {{ end}}
  resources:
    requests:
      storage: {{ .Values.pvc.steamcmd.storageSize }}Gi