apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-instances
spec:
  accessModes:
    - {{ .Values.pvc.instances.accessMode }}
  {{ if .Values.pvc.instances.storageClass }}
  storageClassName: {{ .Values.pvc.instances.storageClass }}
  {{ end}}
  resources:
    requests:
      storage: {{ .Values.pvc.instances.storageSize }}Gi