kind: Service
apiVersion: v1
metadata:
  name: {{lower .Release.Name}}-lb
spec:
  ports:
    - name: http80
      protocol: TCP
      port: 80
      targetPort: 80
    - name: http8080
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: http8096
      protocol: TCP
      port: 8096
      targetPort: 8096
  selector:
    app: {{lower .Release.Name}}
  externalTrafficPolicy: Local
  loadBalancerIP: {{ .Values.service.loadbalancerIp }}
  type: LoadBalancer