kind: Service
apiVersion: v1
metadata:
  name: {{lower .Release.Name}}-lb
spec:
  ports:
    - name: http-antennas
      protocol: TCP
      port: 5004
      targetPort: 5004
  selector:
    app: antennas
  externalTrafficPolicy: Local
  loadBalancerIP: {{ .Values.service.loadbalancerIp }}
  type: LoadBalancer