apiVersion: apps/v1
kind: Deployment
metadata:
  name: antennas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: antennas
  template:
    metadata:
      labels:
        app: antennas
      name: antennas
    spec:
      containers:
        - image: {{ .Values.image.location }}:{{ .Values.image.tag }}
          imagePullPolicy: IfNotPresent
          name: antennas
          ports:
            - containerPort: 5004
              name: http
              protocol: TCP
          envFrom:
            - configMapRef:
                name: antennas
          resources:
            limits:
              cpu: 250m
              memory: 100M
            requests:
              cpu: 50m
              memory: 30M