deployment:
  sleepStart: false
  nodeSelector:
    enabled: false
    nodeName: overlay_me_if_required
  image:
    location: eclipse-mosquitto
    tag: 2.0.18
  resources:
    limits:
      cpu: 128
      memory: 100
    requests:
      cpu: 50
      memory: 64

pvc:
  data:
    accessMode: ReadWriteMany
    #only applied when set
    storageClass:
    #size in Gi
    storageSize: 5
  config:
    accessMode: ReadWriteMany
    #only applied when set
    storageClass:
    #size in Gi
    storageSize: 5

service: 
  ip: 127.0.0.1

configuration: |-    
  per_listener_settings false
  listener 1883
  allow_anonymous true
  persistence true
  persistence_location /mosquitto/data
  autosave_interval 1800
  include_dir /mosquitto/configinc
  log_dest file /tmp/mosquitto.log  