apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: git-tcp-ingress
spec:
  entryPoints:
    - gitssh
  routes:
    - match: HostSNI(`*`)
      services:
        - name: gitea-clusterip
          port: 60000
  tls:
    {{- range .Values.ingress }}
    - hosts:
        - {{ .name }}
      secretName: ssh-{{ .name }}
    {{- end -}}