apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gitea-ingress
  annotations:
    cert-manager.io/cluster-issuer: "selfsigned-ca-issuer"
    traefik.ingress.kubernetes.io/router.entrypoints: "web, websecure"
    traefik.ingress.kubernetes.io/router.tls: "true"
    ingress.kubernetes.io/ssl-force-host: "true"
    ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - {{ .Values.ingress.name }}
      secretName: {{ .Values.ingress.name }}
  rules:
    - host: {{ .Values.ingress.name }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gitea-clusterip
                port:
                  number: 3000