deployment:
  sleepStart: false
  image:
    location: gitea:gitea
    tag: 1.19.0-rootless

pvc:
  data:
    accessMode: ReadWriteMany
    #only applied when set
    storageClass:
    #size in Gi
    storageSize: 5
  config:
    accessMode: ReadWriteMany
    #only applied when set
    storageClass:
    #size in Gi
    storageSize: 5

ingress:
  name: gitea.local

configuration:
  databaseType: "postgres"
  databaseHost: "overlay_me"
  databaseName: "overlay_me"
  databaseUser: "overlay_me"
  databasePassword: "overlay_me"
  disableRegistration: "true"