homepage:
  image:
    repository: ghcr.io/benphelps/homepage

  enableRbac: true

  serviceAccount:
    name: homepage
    create: true

  controller:
    strategy: Recreate

  ingress:
    main:
      enabled: false

  config:
    kubernetes:
      mode: cluster

  persistence:
    logs:
      enabled: true
      type: emptyDir
      mountPath: /app/config/logs

  resources:
    limits:
      memory: 200Mi
      cpu: 200m
