deployment:
  sleepStart: false
  nodeaffinity:
    enabled: false
    node: ""
  image:
    location: devidian/spaceengineers
    tag: winestaging
  env:
    winedebug: "-all"
    instanceName: "Test Instance"
    publicIp: "127.0.0.1"
  resources:
    enabled: false
    requests:
      memory: "8000"
    limits:
      memory: "8000"

service: 
  ip: 127.0.0.1

pvc:
  plugins:
    accessMode: ReadWriteOnce
    storageClass:
    storageSize: 10
  instances:
    accessMode: ReadWriteOnce
    storageClass:
    storageSize: 50
  dedicated:
    accessMode: ReadWriteOnce
    storageClass:
    storageSize: 100
  steamcmd:
    accessMode: ReadWriteOnce
    storageClass:
    storageSize: 5