apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{lower $.Release.Name}}
spec:
  replicas: {{.Values.deployment.replicas}}
  strategy:
    type: {{.Values.deployment.strategy.type}}
  selector:
    matchLabels:
      app: {{lower $.Release.Name}}
  template:
    metadata:
      labels:
        app: {{lower $.Release.Name}}
      name: {{lower $.Release.Name}}
    spec:
      containers:
        - image: {{.Values.deployment.image.location}}:{{.Values.deployment.image.tag}}
          imagePullPolicy: IfNotPresent
          name: youtubedl
          ports:
            - containerPort: 17442
              name: http
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{lower $.Release.Name}}-config
          {{- if .Values.deployment.resources.enabled }}
          resources:
            limits:
              cpu: {{.Values.deployment.resources.limits.cpu}}m
              memory: {{.Values.deployment.resources.limits.memory}}M
            requests:
              cpu: {{.Values.deployment.resources.requests.cpu}}m
              memory: {{.Values.deployment.resources.requests.memory}}M
          {{- end }}
          volumeMounts:
            {{- range .Values.pvc -}}{{ printf "\n" }}
            - name: {{lower $.Release.Name}}-{{.name}}
              mountPath: {{.mountPoint}}
            {{- end }}
      volumes:
        {{- range .Values.pvc -}} {{ printf "\n" }}
        - name: {{lower $.Release.Name}}-{{.name}}
          persistentVolumeClaim:
            claimName: {{lower $.Release.Name}}-{{.name}}
        {{- end }}