vm-agent:
  enabled: false #set to true to enable

victoria-metrics-operator:
  operator:
    disable_prometheus_converter: false
    prometheus_converter_add_argocd_ignore_annotations: false
    psp_auto_creation_enabled: false
    enable_converter_ownership: false
    useCustomConfigReloader: false
  resources:
    limits:
      cpu: 120m
      memory: 320Mi
    requests:
      cpu: 80m
      memory: 120Mi