deployment:
  sleepStart: false
  image:
    location: ghcr.io/sberk42/fritzbox_exporter/fritzbox_exporter
    tag: 6a1199ccb7cc48c0f76fc8027723ebf02b35783c
  resources:
    limits:
      memory: 256
      cpu: 50
  env:
    password: overlay_me
    username: overlay_me
    gateway_url: "http://127.0.0.1:49000"
    listen_address: "0.0.0.0:9042"

service:
  clusterIp:
    enabled: true
  loadbalancer:
    enabled: true
    ip: 127.0.0.1
    

serviceMonitor:
  enabled: false