apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-clusterip
spec:
  type: ClusterIP
  selector:
    app: {{.Release.Name}}
  ports:
    - name: http
      protocol: TCP
      port: 3333
      targetPort: 3333