apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
spec:
  accessModes:
    - ReadWriteMany
  {{ if .Values.pvc.data.storageClass }}
  storageClassName: {{ .Values.pvc.data.storageClass }}
  {{ end}}
  resources:
    requests:
      storage: {{ .Values.pvc.data.storageSize }}Gi