apiVersion: v1
kind: Service
metadata:
  name: hedgedoc-clusterip
spec:
  type: ClusterIP
  selector:
    app: hedgedoc
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080