kind: Service
apiVersion: v1
metadata:
  name: {{.Release.Name}}-lb
spec:
  selector:
    app: {{.Release.Name}}
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  externalTrafficPolicy: Local
  loadBalancerIP: {{ .Values.service.ip }}
  type: LoadBalancer