kind: Service
apiVersion: v1
metadata:
  name: {{lower .Release.Name}}-lb
spec:
  ports:
    - name: http
      protocol: TCP
      port: 2342
      targetPort: 2342
  selector:
    app: {{lower .Release.Name}}
  externalTrafficPolicy: Local
  loadBalancerIP: {{ .Values.service.loadbalancerIp }}
  type: LoadBalancer