kind: Service
apiVersion: v1
metadata:
  name: antennas-clusterip
spec:
  type: ClusterIP
  ports:
    - name: http-antennas
      protocol: TCP
      port: 5004
      targetPort: 5004
  selector:
    app: antennas