kind: Service
apiVersion: v1
metadata:
  name: minecraft-udp
  annotations:
    {{ if .Values.service.ciliumShareIp }}
    io.cilium/lb-ipam-sharing-key: "{{ .Values.service.ciliumShareKey }}"
    io.cilium/lb-ipam-ips: "{{ .Values.service.ip }}"
    {{ end }}
spec:
  selector:
    app: minecraft-vanilla-minecraft
  ports:
    - name: game
      port: 25565
      protocol: UDP
  type: LoadBalancer