apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Release.Name}}-configuration
data:
  GITEA_INSTANCE_URL: {{.Values.configuration.instanceUrl}}
  GITEA_RUNNER_REGISTRATION_TOKEN: {{.Values.configuration.registrationToken}}
  GITEA_INSTANCE_INSECURE: {{.Values.configuration.instanceInsecure}}